/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_sweety_NativeApi */

#ifndef _Included_dev_sweety_NativeApi
#define _Included_dev_sweety_NativeApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_sweety_NativeApi
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_dev_sweety_NativeApi_sum
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     dev_sweety_NativeApi
 * Method:    subtract
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_dev_sweety_NativeApi_subtract
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
