package dev.sweety.processor;

import dev.sweety.nativeapi.Jni;
import dev.sweety.nativeapi.NativeApi;

import javax.annotation.processing.*;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.*;
import javax.lang.model.type.ArrayType;
import javax.lang.model.type.TypeMirror;
import javax.tools.Diagnostic;
import javax.tools.JavaFileObject;
import java.io.IOException;
import java.io.Writer;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Set;

/**
 * Generates, from one {@code @NativeApi} interface, the per-backend JNI holder
 * classes ({@code <Name>Natives}) and a JSON descriptor of {name, jniSig, thunk}.
 * The C++ and Rust builds read that descriptor to emit their RegisterNatives
 * tables, so the native surface is declared exactly once.
 *
 * <p>Pass the descriptor output path with {@code -Anative.descriptor=<file>}.
 */
@SupportedAnnotationTypes("dev.sweety.nativeapi.NativeApi")
@SupportedOptions(NativeApiProcessor.OPT_DESCRIPTOR)
public final class NativeApiProcessor extends AbstractProcessor {

    static final String OPT_DESCRIPTOR = "native.descriptor";

    @Override
    public SourceVersion getSupportedSourceVersion() {
        return SourceVersion.latestSupported();
    }

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment round) {
        for (Element e : round.getElementsAnnotatedWith(NativeApi.class)) {
            if (e.getKind() != ElementKind.INTERFACE) {
                error(e, "@NativeApi only applies to interfaces");
                continue;
            }
            try {
                handle((TypeElement) e);
            } catch (IOException ex) {
                error(e, "code generation failed: " + ex.getMessage());
            }
        }
        return true;
    }

    private void handle(TypeElement iface) throws IOException {
        NativeApi api = iface.getAnnotation(NativeApi.class);
        if (api == null) return;
        String pkg = processingEnv.getElementUtils().getPackageOf(iface).getQualifiedName().toString();
        String ifaceName = iface.getSimpleName().toString();

        List<Method> methods = new ArrayList<>();
        for (Element m : iface.getEnclosedElements()) {
            if (m.getKind() != ElementKind.METHOD) continue;
            ExecutableElement ee = (ExecutableElement) m;
            Jni jni = ee.getAnnotation(Jni.class);
            if (jni == null) {
                error(ee, "method missing @Jni(thunk=...)");
                continue;
            }
            methods.add(Method.of(ee, jni));
        }

        String[] enums = api.backendEnums();
        String[] names = Arrays.stream(enums).map(s -> s.substring(0, 1).toUpperCase() + s.substring(1).toLowerCase()).toArray(String[]::new);
        if (names.length != enums.length) {
            error(iface, "backendNames and backendEnums must have equal length");
            return;
        }
        List<String> holders = new ArrayList<>();
        for (int i = 0; i < names.length; i++) {
            String cls = names[i] + "Natives";
            holders.add(pkg.replace('.', '/') + "/" + cls);
            writeHolder(pkg, cls, ifaceName, enums[i], methods);
        }

        writeDescriptor(pkg, names, holders, methods);
    }

    private void writeHolder(String pkg, String cls, String iface, String backendEnum,
                             List<Method> methods) throws IOException {
        String skel = """
                package %pkg%;
                
                import dev.sweety.Backend;
                import dev.sweety.NativeLib;
                // Generated by NativeApiProcessor. Do not edit.
                final class %cls% implements %iface% {
                    static {
                        NativeLib.loadForJni(Backend.%backendEnum%);
                    }
                
                    private static final %cls% INSTANCE = new %cls%();
                
                    public static %cls% get() {
                        return INSTANCE;
                    }
                
                    private %cls%(){}
                
                """.replace("%pkg%", pkg).replace("%cls%", cls).replace("%iface%", iface).replace("%backendEnum%", backendEnum);
        StringBuilder sb = new StringBuilder(skel);
        for (Method m : methods) {
            sb.append("    @Override public native ").append(m.javaReturn).append(" ")
                    .append(m.name).append("(").append(m.javaParams).append(");\n");
        }
        sb.append("}\n");

        JavaFileObject f = processingEnv.getFiler().createSourceFile(pkg + "." + cls);
        try (Writer w = f.openWriter()) {
            w.write(sb.toString());
        }
    }

    private void writeDescriptor(String pkg, String[] names, List<String> holders,
                                 List<Method> methods) throws IOException {
        String path = processingEnv.getOptions().get(OPT_DESCRIPTOR);
        if (path == null) {
            processingEnv.getMessager().printMessage(Diagnostic.Kind.NOTE,
                    "-A" + OPT_DESCRIPTOR + " not set; skipping JSON descriptor");
            return;
        }
        StringBuilder j = new StringBuilder();
        j.append("{\n  \"backends\": [\n");
        for (int i = 0; i < names.length; i++) {
            j.append("    {\"name\": \"").append(names[i]).append("\", \"holder\": \"")
                    .append(holders.get(i)).append("\"}").append(i + 1 < names.length ? "," : "").append("\n");
        }
        j.append("  ],\n  \"methods\": [\n");
        for (int i = 0; i < methods.size(); i++) {
            Method m = methods.get(i);
            j.append("    {\"name\": \"").append(m.name).append("\", \"sig\": \"").append(m.jniSig)
                    .append("\", \"thunk\": \"").append(m.thunk).append("\", \"critical\": ").append(m.critical)
                    .append("}").append(i + 1 < methods.size() ? "," : "").append("\n");
        }
        j.append("  ]\n}\n");

        Path out = Path.of(path);
        if (out.getParent() != null) Files.createDirectories(out.getParent());
        Files.writeString(out, j.toString());
        processingEnv.getMessager().printMessage(Diagnostic.Kind.NOTE,
                "wrote native descriptor: " + out);
    }

    private void error(Element e, String msg) {
        processingEnv.getMessager().printMessage(Diagnostic.Kind.ERROR, msg, e);
    }

    /**
     * A captured native method: name, JNI signature, thunk symbol, Java decl pieces.
     */
    private record Method(String name, String jniSig, String thunk, boolean critical, String javaReturn,
                          String javaParams) {

        static Method of(ExecutableElement ee, Jni jni) {
            String name = ee.getSimpleName().toString();
            StringBuilder sig = new StringBuilder("(");
            StringBuilder params = new StringBuilder();
            List<? extends VariableElement> ps = ee.getParameters();
            for (int i = 0; i < ps.size(); i++) {
                TypeMirror t = ps.get(i).asType();
                sig.append(jniSig(t));
                if (i > 0) params.append(", ");
                params.append(javaType(t)).append(" p").append(i);
            }
            sig.append(")").append(jniSig(ee.getReturnType()));
            return new Method(name, sig.toString(), jni.thunk(), jni.critical(),
                    javaType(ee.getReturnType()), params.toString());
        }

        private static String jniSig(TypeMirror t) {
            return switch (t.getKind()) {
                case VOID -> "V";
                case BOOLEAN -> "Z";
                case BYTE -> "B";
                case CHAR -> "C";
                case SHORT -> "S";
                case INT -> "I";
                case LONG -> "J";
                case FLOAT -> "F";
                case DOUBLE -> "D";
                case ARRAY -> "[" + jniSig(((ArrayType) t).getComponentType());
                default -> throw new IllegalArgumentException("unsupported JNI type: " + t);
            };
        }

        private static String javaType(TypeMirror t) {
            return switch (t.getKind()) {
                case VOID -> "void";
                case BOOLEAN -> "boolean";
                case BYTE -> "byte";
                case CHAR -> "char";
                case SHORT -> "short";
                case INT -> "int";
                case LONG -> "long";
                case FLOAT -> "float";
                case DOUBLE -> "double";
                case ARRAY -> javaType(((ArrayType) t).getComponentType()) + "[]";
                default -> throw new IllegalArgumentException("unsupported type: " + t);
            };
        }
    }
}
