val cppBuildDir = file("$projectDir/cmake-build")
val hash = project(":examples:hash")
val nativeOutputDir = hash.layout.buildDirectory.dir("natives").get().asFile

// Override with -Pcmake=/path/to/cmake or the CMAKE env var; otherwise use PATH.
val cmakePath: String =
    (project.findProperty("cmake") as String?)
        ?: System.getenv("CMAKE")
        ?: "cmake"

// The C++ JNI surface (thunks + C-ABI lifecycle + RegisterNatives + JNI_OnLoad) is
// generated by the framework processor during :examples:hash:kspKotlin, straight into
// generated/native.generated.cpp. Hand-written: the FNV core (fnv.hpp) and the loop
// C-ABI (transform, batch) in cabi.cpp. CMake just compiles them.
tasks.register<Exec>("configureCpp") {
    description = "Configure the C++ native library using CMake"
    dependsOn(":examples:hash:kspKotlin")
    val javaHome = System.getProperty("java.home")
    // find_package(JNI) locates the platform jni_md.h; only JAVA_HOME is needed
    // as a hint, keeping this portable across Linux / macOS / Windows.
    commandLine(
        cmakePath,
        "-DJAVA_HOME=$javaHome",
        "-B", cppBuildDir.absolutePath,
        "-S", projectDir.absolutePath
    )
}

tasks.register<Exec>("buildCpp") {
    description = "Build the C++ native library using CMake"
    dependsOn("configureCpp")
    commandLine(cmakePath, "--build", cppBuildDir.absolutePath)
    doFirst { nativeOutputDir.mkdirs() }
    doLast {
        copy {
            from(fileTree(cppBuildDir).matching { include("*.dylib", "*.so", "*.dll") })
            into(nativeOutputDir)
        }
    }
}

tasks.register<Delete>("cleanCpp") {
    description = "Clean the C++ build directory and output native library"
    delete(cppBuildDir)
}
