mod cabi;
mod fnv;

// C-ABI lifecycle + jni_* thunks + RegisterNatives + JNI_OnLoad, generated by the
// framework processor during :examples:hash:kspKotlin into src/generated/.
include!("generated/native_generated.rs");
