package dev.sweety.nativegen.gradle

import groovy.json.JsonSlurper
import java.io.File

/**
 * Templates + native type maps for the `scaffold*` tasks. They generate the hand-written native
 * skeleton (build files + a `cabi` stub with every flat C-ABI symbol the processor does NOT
 * generate, i.e. the non-`@Core` ones) so a new project only fills in the algorithm bodies.
 */
object Scaffold {

    /** C-ABI entries the user must hand-write: `@Cabi` methods without a `@Core` op. */
    @Suppress("UNCHECKED_CAST")
    private fun handWritten(descriptor: File): List<Map<String, Any?>> {
        if (!descriptor.isFile) return emptyList()
        val json = JsonSlurper().parse(descriptor) as Map<String, Any?>
        val cabi = (json["cabi"] as? List<Map<String, Any?>>) ?: emptyList()
        return cabi.filter { it["op"] == null }
    }

    private fun params(e: Map<String, Any?>) = (e["params"] as List<String>)

    // --- C++ --------------------------------------------------------------------------------

    private fun cParam(k: String) = when (k) {
        "ptr" -> "void*"; "long" -> "size_t"; "int" -> "int32_t"; "byte" -> "uint8_t"; else -> "void*"
    }
    private fun cRet(k: String) = when (k) {
        "void" -> "void"; "ptr" -> "void*"; "long" -> "uint64_t"; "int" -> "int32_t"; "byte" -> "uint8_t"; else -> "void"
    }
    private fun cDefault(k: String) = when (k) { "void" -> ""; "ptr" -> "return nullptr;"; else -> "return 0;" }

    fun cppCabi(descriptor: File): String = buildString {
        appendLine("// Hand-written native core: fill in the bodies. Generated stub (idempotent).")
        appendLine("#include <cstddef>")
        appendLine("#include <cstdint>")
        appendLine()
        appendLine("extern \"C\" {")
        for (e in handWritten(descriptor)) {
            val sym = e["symbol"] as String
            val sig = params(e).mapIndexed { i, k -> "${cParam(k)} p$i" }.joinToString(", ")
            val body = cDefault(e["ret"] as String).let { if (it.isEmpty()) "/* TODO */" else "/* TODO */ $it" }
            appendLine("${cRet(e["ret"] as String)} $sym($sig) { $body }")
        }
        appendLine("}")
    }

    fun cppCMake() = """
        cmake_minimum_required(VERSION 3.22)
        project(native_cpp LANGUAGES CXX)
        set(CMAKE_CXX_STANDARD 20)
        set(CMAKE_POSITION_INDEPENDENT_CODE ON)
        if(NOT CMAKE_BUILD_TYPE)
            set(CMAKE_BUILD_TYPE Release)
        endif()
        find_package(JNI REQUIRED)
        add_library(native_cpp SHARED
            src/cabi.cpp
            generated/native.generated.cpp
        )
        target_include_directories(native_cpp PRIVATE ${'$'}{JNI_INCLUDE_DIRS})
    """.trimIndent() + "\n"

    // --- Rust -------------------------------------------------------------------------------

    private fun rParam(k: String) = when (k) {
        "ptr" -> "*mut c_void"; "long" -> "usize"; "int" -> "i32"; "byte" -> "u8"; else -> "*mut c_void"
    }
    private fun rRet(k: String) = when (k) {
        "void" -> ""; "ptr" -> " -> *mut c_void"; "long" -> " -> u64"; "int" -> " -> i32"; "byte" -> " -> u8"; else -> ""
    }
    private fun rDefault(k: String) = when (k) { "void" -> ""; "ptr" -> "std::ptr::null_mut()"; else -> "0" }

    fun rustCabi(descriptor: File): String = buildString {
        appendLine("//! Hand-written native core: fill in the bodies. Generated stub (idempotent).")
        appendLine("use std::os::raw::c_void;")
        appendLine()
        for (e in handWritten(descriptor)) {
            val sym = e["symbol"] as String
            val sig = params(e).mapIndexed { i, k -> "p$i: ${rParam(k)}" }.joinToString(", ")
            val def = rDefault(e["ret"] as String)
            val body = if (def.isEmpty()) "/* TODO */" else "/* TODO */ $def"
            appendLine("#[no_mangle]")
            appendLine("pub unsafe extern \"C\" fn $sym($sig)${rRet(e["ret"] as String)} { $body }")
        }
    }

    fun rustCargo(pkg: String) = """
        [package]
        name = "$pkg"
        version = "0.1.0"
        edition = "2021"

        [lib]
        name = "native_rust"
        crate-type = ["cdylib"]

        [dependencies]
        jni = "0.21"
    """.trimIndent() + "\n"

    fun rustLib() = """
        mod cabi;

        // jni_* thunks + RegisterNatives + JNI_OnLoad, generated by the framework processor.
        include!("generated/native_generated.rs");
    """.trimIndent() + "\n"

    /** Write [content] to [file] only if it does not already exist (idempotent). */
    fun writeIfAbsent(file: File, content: String) {
        if (file.exists()) return
        file.parentFile.mkdirs()
        file.writeText(content)
    }
}
